#!/bin/sh /etc/rc.common
# a placer dans /etc/init.d/relaycontrol-light
START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/share/relaycontrol-light/start.sh
    procd_set_param respawn #redemarrage auto en cas de crash
    procd_set_param stdout 1 #redirige les logs vers journal systeme avec logread
    procd_set_param stderr 1
    procd_close_instance
}